### ISSUE TITLE
CRUD AnthropometricEvaluations

### ISSUE THREAD

**Issue by jrtxr** [improdutiva-ltda/healthy-life-api#8]
interface AnthropometricEvaluations {
  PhysicalActivityLevel: number;
  currentWeight: number;

  Circumferenceabdominal: number;
  Circumferencewaist: number;
  Circumferencearm: number;
  Circumferencecalf: number;
  Circumferencehip: number;

  SkinfoldBiceps: number;
  SkinfoldTriceps: number;
  SkinfoldSubscapular: number;
  SkinfoldMediumAxillary: number;
  SkinfoldSuprailiac: number;
  SkinfoldSupraspinal: number;
  SkinfoldAbdominal: number;
  SkinfoldThigh: number;
  SkinfoldCalf: number;
  SkinfoldBreastplate: number;

  createdAt: Date;
  updatedAt: Date;
}

**Comment by Mateus0808** [comment]
Finished

**Comment by Mateus0808** [comment]
Finished
